export default [
  {
    PositionCompany: "Boa Vista Serviços",
    Date: "2021 - Present",
    Description: "Full Stack Developer",
  },
  {
    PositionCompany: "Superare - Web Developer Front-end",
    Date: "Ago 2019 - Mar 2021",
    Description:
      "Componentizing elements with Jade, animation of banner ads and development of e-mail marketing using HTML5",
  },
  {
    PositionCompany:
      "Laureate International Universities - Web Developer Full Stack",
    Date: "Jan 2019 - Ago 2019",
    Description:
      "Developed custom template for Wordpress. API integration with web services. Maintaining Wordpress web pages.",
  },
  {
    PositionCompany: "Temperini Digital - Web Developer Full Stack",
    Date: "2018 - 2019",
    Description:
      "Maintaining the front end of 15 web pages. GIT flow as workflow of version control with the team. Pipeline straigh to Google Cloud as test server. Maintaining SQL data bases. Multiples templates generated by webpack and the codes written in EJS",
  },
];
